### ISSUE TITLE
Upgrade rmp-serde to fix vulnerability

### ISSUE THREAD

**Issue by jqnatividad** [dapper91/ext-sort-rs#11]
First off, thanks for this crate @dapper91 !

I just got a GH dependabot alert regarding `rmp-serde`:

https://github.com/advisories/GHSA-255r-3prx-mf99

Bumping it to the latest release should fix it.

**Comment by dapper91** [comment]
@jqnatividad Hi. Thanks for notification.

**Comment by jqnatividad** [comment]
And thanks for the quick turnaround @dapper91 !
